### ISSUE TITLE
fbad_add_audience: "Low audience"

### ISSUE THREAD

**Issue by bcastane** [daroczig/fbRads#107]
Hi,
i am trying to add audience and appears to be working, but when i enter to facebook appears "Low Audience". I have tried with more thatn 10,000 emails and keep appearing the same issue.

I think that the issue is how i am passing the emails (the structure itself).

Thanks,

`
> mails_upload<-as.character(mails$EMAIL)
> head(mails_upload)
[1] "XXXXX@GMAIL.COM"       "AAAAAAA@GMAIL.COM"
[3] "YYYY@GMAIL.COM"        "BBBBBBBBB@GMAIL.COM"     
[5] "ZZZZZZ@GMAIL.COM"  "CCCCCCCC@GMAIL.COM" 
> fbad_add_audience(fbacc, 123456789, schema = c("EMAIL"), hashes=mails_upload)
INFO [2018-09-14 10:34:43] Adding 1001 EMAIL to 123456789 custom audience ID.
                                                                                                                                                        0 
"{\"audience_id\":\"123456789\",\"session_id\":\"XXXXXXXX\",\"num_received\":1001,\"num_invalid_entries\":0,\"invalid_entry_samples\":{}}" 
> `

**Comment by daroczig** [comment]
That looks like an OK response from FB, so not sure if it's an `fbRads` issues. Did you standardize your e-mail addresses before passing to`fbad_add_audience`, like ` Trimming leading and trailing whitespace and convert all characters to lowercase`? Also, did you wait 1+ hour before checking the matched number of users in the audience? As said above, I don't think it's an `fbRads` issue or if I could help more, so closing -- pls reopen if it turns out to be indeed the R pkg's problem
