### ISSUE TITLE
Update default API version to v3.2

### ISSUE THREAD

**Issue by RickPack** [daroczig/fbRads#113]
Readme Examples that specify a version of the Facebook Ads API cause this error, which might be called "catastrophic" (?) given nothing is returned.
"(#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v3.2."

I plan to offer a pull request soon that simply changes the "version = '3.0" reference to "version = '3.2'", which worked for at least this example:
`accounts <- fbad_get_my_ad_accounts(token, version = '3.2')`

Can you assign this issue to me?

**Comment by daroczig** [comment]
Sorry, but that's a bit more complex -- bumping the default version would require checking the full changelog to see what parts of the current `fbRads` functions are affected: https://developers.facebook.com/docs/graph-api/changelog/version3.2

If there are no breaking changes, then we can bump the version, otherwise some other changes will be required as well. Until then, I'd suggest calling `fbad_init` with your choice of version and all further `fbRads` calls will use that.

**Comment by daroczig** [comment]
sorry, I totally forgot about this one, but bumped the most recent API version to 3.3

**Comment by RickPack** [comment]
Thank you!
