### ISSUE TITLE
fbad_init issue

### ISSUE THREAD

**Issue by danielad-k** [daroczig/fbRads#123]
Hello, 
I get the following error when i try to connect to fbad_init
![image](https://user-images.githubusercontent.com/53984115/83099104-54f4b900-a07a-11ea-93bc-e50d1cb94409.png)

When  I ran, 
debugonce(fbRads:::fbad_request)
fbad_init(accountid=accountid, token=token3, version = "7.0")

I got the following message for curlres$message: 
![image](https://user-images.githubusercontent.com/53984115/83099146-85d4ee00-a07a-11ea-81b0-6231d5d46916.png)
Thank you!

**Comment by daroczig** [comment]
Can you please share your `sessionInfo()` (or `sessioninfo::session_info()` would be even better) after loading `fbRads`?

**Comment by danielad-k** [comment]
Hello, 
Here you go: 
![image](https://user-images.githubusercontent.com/53984115/83139835-fd2a7200-a0ba-11ea-8994-53f327eee9ac.png)

**Comment by danielad-k** [comment]
One more thing: 
the code below actually works too:


library("RCurl")
library("jsonlite")

myURL=paste0("https://graph.facebook.com/v7.0/act_XXXXX/insights?fields&level=ad&",
             "access_token=XXXXXX"
)
print(myURL)
print(getURL(fromJSON(myURL)))

**Comment by daroczig** [comment]
Can you please give a try to #125?

```
devtools::install_github('daroczig/fbRads@ssl_version_6')
```

**Comment by danielad-k** [comment]
Now I get this  error: 
![image](https://user-images.githubusercontent.com/53984115/83143677-5052f380-a0c0-11ea-909a-73e08c18db05.png)

**Comment by daroczig** [comment]
Can you please post the results of `RCurl::curlVersion()`?

**Comment by danielad-k** [comment]
Here you go:
![image](https://user-images.githubusercontent.com/53984115/83153263-c3626700-a0cc-11ea-9958-6d8fb41b9b68.png)

**Comment by daroczig** [comment]
Oh my, that explains -- the OpenSSL version is really old. Probably that's a Windows issue due to the bundled lib in `RCurl`... I should at some point drop `RCurl` and switch to `curl` or `httr` anyway ... but it's a larger change that I won't do in the near future (and if I do, probably will go with `reticulate` and the Python FB Business SDK integration), so no quick fixes for this, sorry.

What you could try is building `RCurl` with a most recent version of OpenSSL or using the package from Linux meanwhile. I will think about a better solution for this, sorry that this is not that helpful.

**Comment by danielad-k** [comment]
thank you. This gives me direction of what to fix.
