### ISSUE TITLE
How to specify the date range for fb_insights?

### ISSUE THREAD

**Issue by simran-k** [daroczig/fbRads#29]
For all ad-accounts using fb_insights API at ad level, 

I get 
date_start = 2016-07-26
and 
date_end = 2016-08-24

Today is 2016-08-24 so I suppose that is its default date range. 

Why is it? How do I get the historical data?
Also, I will append it for every day eventually so would need to fetch it day by day. 

So, 
1. I need to get lifetime data to start with
2. I need to get data incrementally up until last date

**Comment by daroczig** [comment]
`fb_insights` is just a wrapper for the related API endpoint, where you can pass any parameters via `...` -- based on this, there are no docs in the `fbRads` package on how to specify eg the date range, but https://developers.facebook.com/docs/marketing-api/insights/parameters/v2.6 provides some good examples.

There you can see that the default value for `date_preset` is `last_30_days` -- that's why you get the above numbers. I hope you can set the date range based on the above docs, but let me know if you need helpt with this.

**Comment by simran-k** [comment]
Hey, thanks, I got it. But when I try to get lifetime data with date_preset="lifetime" and time_increment=1, it still gets me data from earliest_date to current date for a record and does not step one day in a row/record. Why is that?

**Comment by daroczig** [comment]
Not sure, can you please provide some reproducible example for the error? Eg the below works perfectly fine:

``` r
fb_insights(date_preset = 'lifetime', time_increment = 1, level = 'ad', fields = toJSON(c('impressions', 'total_actions')))
```

I'm closing this now, but happy to reopen if you can post some example code for the erroneous case.
