### ISSUE TITLE
Error in fb_insights:  An unknown error occurred

### ISSUE THREAD

**Issue by simran-k** [daroczig/fbRads#34]
My code used to work just fine and now it's failing at fb_insights call.

`ERROR [2016-09-22 10:19:19] This is a temporary  FB error.
INFO [2016-09-22 10:19:21] Retrying query for the 1  st/nd/rd time
ERROR [2016-09-22 10:19:33] This is a temporary  FB error.
INFO [2016-09-22 10:19:35] Retrying query for the 2  st/nd/rd time
ERROR [2016-09-22 10:19:41] This is a temporary  FB error.
INFO [2016-09-22 10:19:43] Retrying query for the 3  st/nd/rd time
ERROR [2016-09-22 10:19:50] This is a temporary  FB error.
Error in fb_insights(level = "ad", time_range = sprintf("{'since':%s,'until':%s}",  : 
  An unknown error occurred
`

I have tried a couple of times and it continues to fail somehow. How do I avoid this? If it's a temporary error, how do I check the response header for status and ask it to make the call again if it still fails?

My call looks like this :  1: 

`FBInsights <- fb_insights(level = 'ad', time_range="{'since':\"2016-09-21\",'until':\"2016-09-21\"}", time_increment= 1);`

Edit: I tried it for like 7th time and then it worked so I absolutely need to be able to check the response header and recall it if it fails

**Comment by daroczig** [comment]
You can check `fbRads:::fbad_request` for the internals and do the query with more logging, or just check the code at https://github.com/cardcorp/fbRads/blob/master/R/fb_init.R#L238 to see when the fn retries the query.

Based on my past experience, FB often fails to reply with proper error msg (eg when the amount of data you try to query via a sync call is too large so you should do an async query) and throws those useless error messages. For your problem, the easiest workaround is doing an async Insights query instead of the default sync one (BTW that should happen since ff0e42dc071e3e22cee43eb2447567667b74737e).

Please let me know if this help.

**Comment by simran66** [comment]
@daroczig : Hey, Thanks. Looked into the asynch request but when most of the times it fails, it is fetching data for only like a day. It fails randomly. Could I get an example may be where fbad_request is used ?

**Comment by simran66** [comment]
Also, I just keep getting : 

`ERROR [2016-10-03 01:17:43] This is a temporary  FB error.
INFO [2016-10-03 01:17:45] Retrying query for the 1  st/nd/rd time
ERROR [2016-10-03 01:17:51] This is a temporary  FB error.
INFO [2016-10-03 01:17:53] Retrying query for the 2  st/nd/rd time
ERROR [2016-10-03 01:17:58] This is a temporary  FB error.
INFO [2016-10-03 01:18:00] Retrying query for the 3  st/nd/rd time
ERROR [2016-10-03 01:18:06] This is a temporary  FB error.
Error in fb_insights(level = "ad", time_range = sprintf("{'since':%s,'until':%s}",  : 
  An unknown error occurred`

retries argument is for internal use but is there a way I could specify the number of times it should retry instead? I tried setting retries in negative :P hoping it was only initializing by the value passed and incrementing by one but glad that it has been smartly coded to avoid that :) Please do let me know since I am using it to automate data import and these failures are giving me really hard time

@daroczig

**Comment by daroczig** [comment]
@simran66 the sync query can (often) fail fetching even short amount of time's of data -- especially with many (even deleted) ads on an account. I opened an FB ticket on this, followed many similar reports, but the only workaround is to do an async query. It's a bit slower, but at least works. Have you tried that?

Also, are you using the most recent dev version of `fbRads`? The failed sync query should trigger an async one since ~Aug 2016

**Comment by daroczig** [comment]
Closing ticket as I think the problem was resolved in Aug. Please reopen if you still having issues with the dev version of the package.
