### ISSUE TITLE
Name of facebook campaigns not updated

### ISSUE THREAD

**Issue by simran66** [daroczig/fbRads#37]
So, the campaigns were created as a copy of the campaign (since it's easier to do it that way) on the dashboard and then the names were updated. 

The campaign names from API look like:

fb_campaign_name-COPY and I never get the updated names. How do we resolve this please?Is that the expected behavior? Is there a workaround for this?

**Comment by daroczig** [comment]
That's highly unexpected as the name (and all other attributes) of a campaign should be the same both returned by the API or shown in the UI. I'd open an FB platform bug report with a screenshot + campaign ID + API response so that they can debug -- I'm not sure if there's anything we can do about this in the R package, so I'm closing this, but please reopen with some more information if you think it's related to the R pkg.
