### ISSUE TITLE
refreshing the token using fbrads

### ISSUE THREAD

**Issue by simran-k** [daroczig/fbRads#38]
I had created this issue here : https://github.com/cardcorp/fbRads/issues/17

The suggested fix was to copy the token from localhost initially and then use it on remote server which I did. But now that my token has expired, do I ought to do it every-time it expires?   That isn't really a fix. Do we have a proper fix for this?

We need it guys :) How do we do without getting authentication to work properly.

**Comment by daroczig** [comment]
Not sure if `fbRads` can help you refreshing the token, it's rather an infra question.

Either you have a long-lived token and do frequent/regular queries (eg hit the Insights API endpoint at least once a week), so that your token does not expire, or you can generate a token that never expires with Standard access to Facebook's Marketing API -- which is I suppose the case if you are using `fbRads` for production. Right?

See https://developers.facebook.com/docs/facebook-login/access-tokens/#termtokens
Does it help?

**Comment by simran-k** [comment]
Oh, we actually do the quiery every day without fail.It still got expired. Yes, I am using fbRads for production and would like to have access to a token that isn't going to expire. I had a long term token and hence it lived for quite a long but may be after 60 days , it did expire. But does that still mean that I got to update it every 60 days?I was hoping to have sort of a permanent fix for this.

**Comment by daroczig** [comment]
@simran-k I'm closing this as based on the above-referenced document, having Standard access to the FB API should allow you to get a token without an expiration date. I can confirm this works in production. If you need any further pointers, please let me know, and I will try to look up how we generated these tokens.
