### ISSUE TITLE
Problems with fbad_list_ad when there are more than 1000 ads

### ISSUE THREAD

**Issue by thomiko** [daroczig/fbRads#79]
I would like to point out that a call to fbad_list_ad throws an error if there are more than 1000 ads in a FB account and if the display parameter is set to TRUE or has been omitted (defaults to TRUE):

![fbrads - fbad_list_ad](https://user-images.githubusercontent.com/16490122/35269878-ad951f90-002d-11e8-973b-8c2a149a69d7.png)

This is the error message:

![fbrads - error](https://user-images.githubusercontent.com/16490122/35269901-c2009cde-002d-11e8-8ad3-de7ad239b925.png)

This is the result as a list:

![fbrads - list](https://user-images.githubusercontent.com/16490122/35269923-cf8d6fa8-002d-11e8-9ba9-69a2dcdb9c35.png)

It seems to me that if you have more than 1000 ads then fbRads creates more than 1 dataframe and those dataframes can't be added together properly when using simplify = TRUE

**Comment by daroczig** [comment]
Yeah, good point - if the API returns a `list` of `data.frame`s including nested `data.frame`s, then the internal `fbRads` functions are not smart enough to handle this -- that's why we introduced the `simplify = FALSE` option, so that you can post-process the results based on your needs. FTR I don't think that there's a general solution for nested `data.frame`s -- as there are so many different fields to be queried at the API, so I don't think that we'll have a general solution for this.

Having said that, thanks a lot for the report, but I'm going to close this for now.
If you have any suggestions on how to handle the nested data formats in a general way, pls reopen or create a new ticket. Thanks!
